name       : libsodium
version    : 1.0.16
release    : 3
source     :
    - https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz : eeadc7e1e1bcef09680fb4837d448fbdf57224978f865ac1c16745868fbd0533
license    : ISC
component  : security.library
summary    : Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
description: |
    Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
setup      : |
    %configure --disable-asm --disable-opt --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
