name       : libsodium
version    : 1.0.18
release    : 7
source     :
    - https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz : 6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1
license    : ISC
component  : security.library
summary    : Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
description: |
    Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
setup      : |
    %configure --disable-opt --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
