name       : libsodium
version    : 1.0.3
release    : 1
source     :
    - https://github.com/jedisct1/libsodium/archive/1.0.3.tar.gz : 5346eec127d136bd73a25f72f16c71ed7520e992d16a5fd3efa927a909151e1e
license    : ISC
summary    : Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
description: |
    Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
builddeps  :
libsplit : no
setup      : |
    ./autogen.sh --prefix=/usr
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
