name       : libsodium
version    : 1.0.4
release    : 2
source     :
    - https://github.com/jedisct1/libsodium/releases/download/1.0.4/libsodium-1.0.4.tar.gz : e4f75d4b2bd860068e0401163207415c9d41048d7601409897ff2951839fd310
license    : ISC
summary    : Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
description: |
    Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
builddeps  :
libsplit : no
setup      : |
    ./autogen.sh --prefix=/usr
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
